task: sample_huggingface
dataset_path: "data/docs"
processors: ["tables", "breaks"]
embedding: 
  provider: "huggingface"
  model: "sentence-transformers/all-roberta-large-v1"  # all-MiniLM-L6-v2 | all-mpnet-base-v2
  device: "auto"  
  batch_size: 32
  max_seq_length: 1024
  normalize: true
  dimension_reduction: {type: "PCA", dims: 512}   

storage: 
  text_store: "sqlite"
  vector:
    upload: false
    clear: false
    index: "sec-embeddings"
  outputs: ["chunks", "documents"]


generator: {provider: "openai", model: "gpt-4o-mini"}
judge:
  type: "llm"
  prompt: "You are a strict grader. Score 1-5 for relevance and faithfulness..."
  calibration: {gold_fraction: 0.1}
retrival: {type: "cosine", top_k: 10}
