task: sample
dataset_path: "data/"
processors: ["tables", "breaks"] # toc
embedding: 
  provider: "openai"
  model: "text-embedding-3-small"
  pooling_strategy: "mean"  # mean, max, weighted, smooth_decay
  dimension_reduction: {type: "PCA", dims: 512}   # UMAP / T-SNE
  use_threading: true
  max_workers: 8

storage: 
  text_store: "sqlite"
  vector:
    upload: true
    clear: true
    index: "sec-embedding"
  outputs: ["chunks", "documents"]

report:
  output_path: "evals/reports/sample"

generator: {provider: "openai", model: "gpt-4o-mini"}
judge:
  type: "llm"
  prompt: "You are a strict grader. Score 1-5 for relevance and faithfulness..."
  calibration: {gold_fraction: 0.1}
retrival: {type: "cosine", top_k: 10}
